from django.urls import path
from . import views
from .views import (ShopratingAPI,
ShopprofileAPIView, 
ListvoucherAPI,ListcomboAPI,
ListdealshockAPI,
ListprogramAPI,
ListflashsaleAPI,
Listordershop,
Newvoucher,
DetailVoucher,
NewcomboAPI,
DetailComboAPI,
NewDeal,
Updatevariation,
DetailDeal,
NewprogramAPI,
Detailprogram,
Newflashsale,
DetailFlashsale,
Updateitem,
NewItem,
Createclassify,
Listproduct,
NewShopAwardAPI,
UpdateclassifyAPI,
DetailShopAwardAPI,
NewFollowOffer,
DetailFollowOffer,
ListFollowOfferAPI,
Createcategory,
Updateorder,
ListShopAwardAPI
)
urlpatterns = [
    path("infoseller", views.infoseller),
    path("product/", views.product),
    path("addcategory", Createcategory.as_view()),
    
    path("shop/rating",ShopratingAPI.as_view()),
    path("vouchers/list", ListvoucherAPI.as_view()),
    path("bundle/list", ListcomboAPI.as_view()),
    path("follow-prize/list", ListFollowOfferAPI.as_view()),
    path("shop-game/list", ListShopAwardAPI.as_view()),
    path("add-on-deal/list", ListdealshockAPI.as_view()),
    path("list/discount", ListprogramAPI.as_view()),
    path("shop-flash-sale/list", ListflashsaleAPI.as_view()),
    path("product/list", views.get_product),
    path("product/list/app", Listproduct.as_view()),
    path("variation/create", Createclassify.as_view()),
    path("classify/update", UpdateclassifyAPI.as_view()),
    
    path("variation/update", Updatevariation.as_view()),
    path("product/<int:id>", Updateitem.as_view()),
    path("product/update_image", views.update_image),
    path("product/category", NewItem.as_view()),
    path("product/delete", views.delete_product),
    path("shipping/list", views.shipping),
    path("shipping/shop/list", views.get_shipping),
    path("shop/create", views.create_shop),
    path('voucher/new',Newvoucher.as_view()),
    path('voucher/<int:id>',DetailVoucher.as_view()),
    path("follow-prize/new", NewFollowOffer.as_view()),
    path("follow-prize/<int:id>", DetailFollowOffer.as_view()),
    path("shop-game/new", NewShopAwardAPI.as_view()),
    path("shop-game/<int:id>", DetailShopAwardAPI.as_view()),
    path("discount/create", NewprogramAPI.as_view()),
    path("discount/<int:id>",Detailprogram.as_view()),
    path("new_combo", NewcomboAPI.as_view()),
    path("combo/<int:id>", DetailComboAPI.as_view()),
    path("flashsale/create", Newflashsale.as_view()),
    path("flashsale/<int:id>", DetailFlashsale.as_view()),
    path("new_deal", NewDeal.as_view()),
    path('deal_shock/<int:id>',DetailDeal.as_view()),
    path("home/seller", views.homeseller),
    path("shop/profile",ShopprofileAPIView.as_view()),
    path("shop/order",Listordershop.as_view()),
    path("orders",Updateorder.as_view()),
    
]