from django.urls import path
from . import views
from django.conf.urls import include
from rest_framework_simplejwt import views as jwt_views
from .views import (
    ChangePasswordView,
    HomeAPIView,
    CategoryListView,
    ImageHomeAPIView,
    RefreshTokenuser,
    ListItemRecommendAPIView,
    SetNewPasswordAPIView,
    PasswordResetView,
    ProductInfoAPI,
    CartItemAPIView,
    UpdateCartAPIView,
    OrderinfoAPIView,
    AddToCardBatchAPIView,
    DealShockAPIView,
    PromotionAPIView,
    CheckoutAPIView,
    Category_home,
    CartAPIView,
    ListorderAPIView,
    AddToCartAPIView,
    SearchitemAPIView,
    ShoporderAPI,
    PurchaseAPIView,
    AddressAPIView,
    Listitemseller,
    UserView,
    Itemrecently,
    Registeremail,
    VerifyEmailView,
    Sendotp,VerifySMSView,
    Topsearch,
    RegisterView, LoginView, LogoutView ,
    UpdateOnline,
    ActionReviewAPI,
    BuyagainAPI,
    Byproductdeal,
    ItemdetailAPI,
    ShopdetailAPI,
    CategorydetailAPI,
    ShopinfoAPI,
    FlashsaleAPI,
    ProfileAPI,
    ListFlashsaleAPI,
    PaymentAPIView,
    ListTrendsearch,
    CategoryinfoAPI,
    SearchitemshopAPI,
    Updatecategory,
    CityAPI
  
)

urlpatterns = [
    
    path(
        "reset/password/", views.PasswordResetView.as_view(), name="rest_password_reset"
    ),
     path(
        'password-reset/<uidb64>/<token>/',
        views.SetNewPasswordAPIView.as_view(),
        name="password-reset-confirm",
    ),
    path("refresh", jwt_views.TokenRefreshView.as_view()),
    path('register/email', Registeremail.as_view()),
    path('verify/email', VerifyEmailView.as_view()),
    path('register', RegisterView.as_view()),
    path('login', LoginView.as_view()),
    path('update/online', UpdateOnline.as_view()),
    path("verify-sms", views.VerifySMSView.as_view()),
    path("resend-sms", views.Sendotp.as_view()),
    path('logout', LogoutView.as_view()),
    path('user-id/', UserView.as_view()),
    path('top-search',Topsearch.as_view()),
    path('change/password/', ChangePasswordView.as_view()),
    path('products', HomeAPIView.as_view()),
    path('category/home',Category_home.as_view()),
    path('trendsearch',ListTrendsearch.as_view()),
    path('update/image', views.update_image),
    path('update/category', Updatecategory.as_view()),
    
    path('item/recently',Itemrecently.as_view()),
    path('item/bestseller', Listitemseller.as_view()),
    path('product/recommend', ListItemRecommendAPIView.as_view()),
    path('review/<int:id>', ActionReviewAPI.as_view()),
    path('buy_again', BuyagainAPI.as_view()),
    path('imagehome', ImageHomeAPIView.as_view()),
    path('categories', CategoryListView.as_view()),
    path('shop/search', SearchitemshopAPI.as_view()),
    path('deal/byproduct/<int:id>', Byproductdeal.as_view()),
    path('add-to-cart', AddToCartAPIView.as_view()),
    path('cart', CartAPIView.as_view()),
    path('flash_sale', FlashsaleAPI.as_view()),
    path('flash_sale/list', ListFlashsaleAPI.as_view()),
    path('listorder',  ListorderAPIView.as_view()),
    path('order/<int:id>',  OrderinfoAPIView.as_view()),
    path('category/<slug>',CategorydetailAPI.as_view()),
    path('item/get',ItemdetailAPI.as_view()),
    path('shop/get',ShopdetailAPI.as_view()),
    path('shopinfo',ShopinfoAPI.as_view()),
    path('categoryinfo',CategoryinfoAPI.as_view()),
    path('productinfo/<int:id>',ProductInfoAPI.as_view()),
    path('addon-deal-selection/<int:deal_id>/<int:id>', DealShockAPIView.as_view()),
    path('bundle-deal/<int:id>', PromotionAPIView.as_view()),
    path('add-to-cart-batch',AddToCardBatchAPIView.as_view()),
    path('search', SearchitemAPIView.as_view()),
    path('upload-file',views.upload_file),
    path('profile',ProfileAPI.as_view()),
    path('purchase',PurchaseAPIView.as_view()),
    path('cartview',CartItemAPIView.as_view()),
    path('shop/order',ShoporderAPI.as_view()),
    path('updatecart',UpdateCartAPIView.as_view()),
    path('checkout', CheckoutAPIView.as_view()),
    path('payment', PaymentAPIView.as_view()),
    path('save_voucher',views.save_voucher),
    path('update_address',AddressAPIView.as_view()),
    path('get_city',CityAPI.as_view()),  
]